### PR TITLE
No $guarded Attributes Sniff

### LINKED ISSUE #7: No $guarded Attribute Sniff
Some projects avoid using the `$guarded` attribute on models so that any fillable attributes have to be explicitly defined.

A sniff to check for the use of `$guarded` should be relatively simple to check, as any usage of it could trigger a failure.

Simply failing on any use of an attribute called `guarded` could lead to false positives if non Eloquent classes have said attribute. I've never encountered a Laravel project that uses `guarded` for anything other than an Eloquent model though, so maybe worrying about false positives should be something that happens when we actually have a scenario like that.

### PR DESCRIPTION
**Pull request by nathanheffley**
This PR adds a `Models\NoGuardedAttributes` sniff, which simply checks for any `protected $guarded` attributes on classes and fails if it finds it. This would resolve #7.

### CODE REVIEW

File: DealerInspireLaravelCodingStandard/Sniffs/Models/NoGuardedAttributesSniff.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+     *
+     * @param  File $phpcsFile The current file being checked.
+     * @param  mixed $stackPtr  The position of the current token in the stack passed in $tokens. Type of mixed due to the interface not enforcing int.
+     * @return void
+     */
+    public function process(File $phpcsFile, $stackPtr): void
+    {
+        $tokens = $phpcsFile->getTokens();
+
+        $variablePointer = $phpcsFile->findNext([T_VARIABLE], $stackPtr);
```
Comment (DynamoGeek) [inline DealerInspireLaravelCodingStandard/Sniffs/Models/NoGuardedAttributesSniff.php]: 🔥 `->findNext`

Comment (nathanheffley) [reply DealerInspireLaravelCodingStandard/Sniffs/Models/NoGuardedAttributesSniff.php]: Yeah, I really wanted to see if there was some way to avoid having variables and loops and reset stuff so I spent some time digging through some of the more simple Slevomat rules. They have a lot of helper functions that we don't have access to, but I found this gem buried in there somewhere. Really nice when you use something that _has_ to have a specific token after it eventually.
